#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
	opt.load('compiler_c gnu_dirs glib2')
	opt.load('unites', tooldir='.wafcustom')

def configure(cfg):
	cfg.load('compiler_c gnu_dirs glib2')
	cfg.load('unites', tooldir='.wafcustom')


def build(bld):
	bld.load('compiler_c gnu_dirs glib2')
	bld.load('unites', tooldir='.wafcustom')
	test_screenshot = bld.program(
		features = ['c', 'glib2', 'unites'],
		target = 'test-screenshot',
		source = ['screenshot.c'],
		includes = ['src/'],
		export_includes = ['src/'],
		use = 'objects',
		uselib = 'M GOBJECT GLIB GTK3',
		install_path = None
	)

	test_dynamic = bld.program(
		features = ['c', 'glib2'],
		target = 'test-dynamic',
		source = ['dynamic.c'],
		includes = ['src/'],
		export_includes = ['src/'],
		use = 'objects',
		uselib = 'M GOBJECT GLIB GTK3',
		install_path = None
	)

	test_glade = bld.program(
	    features = ['c', 'glib2'],
	    target = 'test-glade-line',
	    source = ['glade-line.c'],
	    includes = ['src/'],
	    export_includes = ['src/'],
	    use = 'objects',
	    uselib = 'M GOBJECT GLIB GTK3',
	    install_path = None
	)
