#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
	opt.load('compiler_c gnu_dirs glib2')

def configure(cfg):
	cfg.load('compiler_c gnu_dirs glib2')

def build(bld):
	bld.load('compiler_c gnu_dirs glib2')

	includes = ['../src']

	test_screenshot = bld.program(
		features = ['c', 'glib2'],
		target = 'test-screenshot',
		source = ['screenshot.c'],
		includes = includes,
		export_includes = includes,
		use = 'objects',
		uselib = 'M GOBJECT GLIB GTK3',
		install_path = None
	)

	test_dynamic = bld.program(
		features = ['c', 'glib2'],
		target = 'test-dynamic',
		source = ['dynamic.c'],
		includes = includes,
		export_includes = includes,
		use = 'objects',
		uselib = 'M GOBJECT GLIB GTK3',
		install_path = None
	)

	test_glade = bld.program(
	    features = ['c', 'glib2'],
	    target = 'test-glade-line',
	    source = ['glade-line.c'],
	    includes = includes,
	    export_includes = includes,
	    use = 'objects',
	    uselib = 'M GOBJECT GLIB GTK3',
	    install_path = None
	)
