#! /usr/bin/env python3
# encoding: utf-8

from waflib import Logs

def options(opt):
	opt.load('gnu_dirs')
	opt.add_option('--no-glade-dtd-check', action='store_false', dest='glade_dtd_check', default=False, help='enable the glade dtd check')
	opt.add_option('--glade-dtd-check', action='store_true', dest='glade_dtd_check', help='disable the glade dtd check')

def configure(cfg):
	cfg.load('gnu_dirs')
	if cfg.options.glade_dtd_check:
		cfg.find_program('xmllint', var='XMLLINT')

def build(bld):
	bld.load('gnu_dirs')

	if bld.options.glade_dtd_check:
		bld(rule="${XMLLINT} --dtdvalid ${DATADIR}/glade/catalogs/glade-catalog.dtd ${SRC} > /dev/null",
			source='goatplot.xml',
			install_path='${DATADIR}/glade/catalogs')
	else:
		bld.install_files('${DATADIR}/glade/catalogs/', 'goatplot.xml')

